// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RenuMate.Api.Persistence;

#nullable disable

namespace RenuMate.Api.Migrations
{
    [DbContext(typeof(RenuMateDbContext))]
    [Migration("20260130192726_add tags")]
    partial class addtags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RenuMate.Api.Entities.PendingEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsSent", "RetryCount");

                    b.ToTable("PendingEmails", (string)null);
                });

            modelBuilder.Entity("RenuMate.Api.Entities.ReminderOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ReminderRuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsSent", "ScheduledAt");

                    b.HasIndex("ReminderRuleId", "ScheduledAt");

                    b.ToTable("ReminderOccurrences", (string)null);
                });

            modelBuilder.Entity("RenuMate.Api.Entities.ReminderRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysBeforeRenewal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<TimeSpan>("NotifyTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("interval")
                        .HasDefaultValue(new TimeSpan(0, 9, 0, 0, 0));

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("SubscriptionId", "NotifyTimeUtc", "DaysBeforeRenewal")
                        .IsUnique();

                    b.ToTable("ReminderRules", (string)null);
                });

            modelBuilder.Entity("RenuMate.Api.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CancelLink")
                        .HasColumnType("text");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("USD");

                    b.Property<int?>("CustomPeriodInDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMuted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PicLink")
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Monthly");

                    b.Property<DateOnly>("RenewalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("TrialPeriodInDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.HasIndex("UserId", "StartDate");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("RenuMate.Api.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsSystem");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsSystem\" = true");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4aa91298-37a1-46e8-b1f8-5b31882c6c7e"),
                            Color = "#E91E63",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Streaming"
                        },
                        new
                        {
                            Id = new Guid("e9e68348-dcd2-4904-b1b1-91a1883c720c"),
                            Color = "#9C27B0",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = new Guid("b2f40faa-f537-4020-9792-b79874e747ec"),
                            Color = "#673AB7",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "News & Media"
                        },
                        new
                        {
                            Id = new Guid("d545838b-28b2-4fbc-9191-35f9bf968c5f"),
                            Color = "#2196F3",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Work"
                        },
                        new
                        {
                            Id = new Guid("7f6b33d8-d0ad-4f28-9ff1-059cc7e1bde7"),
                            Color = "#03A9F4",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("20b1723d-b723-4f54-9d7f-b72accf8ecae"),
                            Color = "#FF9800",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("10e9d371-e94f-4f81-b739-94a3038803df"),
                            Color = "#4CAF50",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = new Guid("f3b512f7-a07a-45b8-b9f1-604cb574ae27"),
                            Color = "#8BC34A",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("9eb8c6c5-fb75-48cb-8886-bffa682de635"),
                            Color = "#FF5722",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Food & Drinks"
                        },
                        new
                        {
                            Id = new Guid("670f7a67-07a5-4941-940f-e29150da1037"),
                            Color = "#00BCD4",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Telephony"
                        },
                        new
                        {
                            Id = new Guid("538ac968-6ab4-4341-9777-dec6f9eb4fb4"),
                            Color = "#607D8B",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Cloud Storage"
                        },
                        new
                        {
                            Id = new Guid("97f23909-edff-4401-ae5f-0747587d136c"),
                            Color = "#3F51B5",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Security"
                        },
                        new
                        {
                            Id = new Guid("a40355c0-87e9-4558-abe7-22ea6c4da41d"),
                            Color = "#795548",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Household"
                        },
                        new
                        {
                            Id = new Guid("62e4982e-4875-49f6-8fab-2634cd26489e"),
                            Color = "#FFC107",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = new Guid("c30588eb-c063-410f-985c-2c9ff063d2fc"),
                            Color = "#009688",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = new Guid("de3e6465-7993-4a55-8ab7-792b107ebe17"),
                            Color = "#F44336",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystem = true,
                            Name = "Pets"
                        });
                });

            modelBuilder.Entity("RenuMate.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMetadataSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Id")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SubscriptionTag", b =>
                {
                    b.Property<Guid>("SubscriptionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("SubscriptionsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("SubscriptionTags", (string)null);
                });

            modelBuilder.Entity("RenuMate.Api.Entities.ReminderOccurrence", b =>
                {
                    b.HasOne("RenuMate.Api.Entities.ReminderRule", "ReminderRule")
                        .WithMany("ReminderOccurrences")
                        .HasForeignKey("ReminderRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReminderRule");
                });

            modelBuilder.Entity("RenuMate.Api.Entities.ReminderRule", b =>
                {
                    b.HasOne("RenuMate.Api.Entities.Subscription", "Subscription")
                        .WithMany("Reminders")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("RenuMate.Api.Entities.Subscription", b =>
                {
                    b.HasOne("RenuMate.Api.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SubscriptionTag", b =>
                {
                    b.HasOne("RenuMate.Api.Entities.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RenuMate.Api.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RenuMate.Api.Entities.ReminderRule", b =>
                {
                    b.Navigation("ReminderOccurrences");
                });

            modelBuilder.Entity("RenuMate.Api.Entities.Subscription", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("RenuMate.Api.Entities.User", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
