namespace RenuMate.Enums;

public enum Currency
{
    AED = 1,   // United Arab Emirates Dirham
    AFN = 2,   // Afghan Afghani
    ALL = 3,   // Albanian Lek
    AMD = 4,   // Armenian Dram
    ANG = 5,   // Netherlands Antillean Guilder
    AOA = 6,   // Angolan Kwanza
    ARS = 7,   // Argentine Peso
    AUD = 8,   // Australian Dollar
    AWG = 9,   // Aruban Florin
    AZN = 10,  // Azerbaijani Manat
    BAM = 11,  // Bosnia-Herzegovina Convertible Mark
    BBD = 12,  // Barbados Dollar
    BDT = 13,  // Bangladeshi Taka
    BGN = 14,  // Bulgarian Lev
    BHD = 15,  // Bahraini Dinar
    BMD = 16,  // Bermudian Dollar
    BND = 17,  // Brunei Dollar
    BOB = 18,  // Bolivian Boliviano
    BRL = 19,  // Brazilian Real
    BSD = 20,  // Bahamian Dollar
    BTN = 21,  // Bhutanese Ngultrum
    BWP = 22,  // Botswana Pula
    BYN = 23,  // Belarusian Ruble (skipped if you want no rubles)
    BZD = 24,  // Belize Dollar
    CAD = 25,  // Canadian Dollar
    CDF = 26,  // Congolese Franc
    CHF = 27,  // Swiss Franc
    CLP = 28,  // Chilean Peso
    CNY = 29,  // Chinese Yuan
    COP = 30,  // Colombian Peso
    CRC = 31,  // Costa Rican Colón
    CUP = 32,  // Cuban Peso
    CVE = 33,  // Cape Verdean Escudo
    CZK = 34,  // Czech Koruna
    DJF = 35,  // Djiboutian Franc
    DKK = 36,  // Danish Krone
    DOP = 37,  // Dominican Peso
    DZD = 38,  // Algerian Dinar
    EGP = 39,  // Egyptian Pound
    ERN = 40,  // Eritrean Nakfa
    ETB = 41,  // Ethiopian Birr
    EUR = 42,  // Euro
    FJD = 43,  // Fijian Dollar
    FKP = 44,  // Falkland Islands Pound
    GBP = 45,  // British Pound Sterling
    GEL = 46,  // Georgian Lari
    GGP = 47,  // Guernsey Pound
    GHS = 48,  // Ghanaian Cedi
    GIP = 49,  // Gibraltar Pound
    GMD = 50,  // Gambian Dalasi
    GNF = 51,  // Guinean Franc
    GTQ = 52,  // Guatemalan Quetzal
    GYD = 53,  // Guyanese Dollar
    HKD = 54,  // Hong Kong Dollar
    HNL = 55,  // Honduran Lempira
    HRK = 56,  // Croatian Kuna
    HTG = 57,  // Haitian Gourde
    HUF = 58,  // Hungarian Forint
    IDR = 59,  // Indonesian Rupiah
    ILS = 60,  // Israeli New Shekel
    IMP = 61,  // Isle of Man Pound
    INR = 62,  // Indian Rupee
    IQD = 63,  // Iraqi Dinar
    IRR = 64,  // Iranian Rial
    ISK = 65,  // Icelandic Króna
    JEP = 66,  // Jersey Pound
    JMD = 67,  // Jamaican Dollar
    JOD = 68,  // Jordanian Dinar
    JPY = 69,  // Japanese Yen
    KES = 70,  // Kenyan Shilling
    KGS = 71,  // Kyrgyzstani Som
    KHR = 72,  // Cambodian Riel
    KID = 73,  // Kiribati Dollar
    KMF = 74,  // Comorian Franc
    KRW = 75,  // South Korean Won
    KWD = 76,  // Kuwaiti Dinar
    KYD = 77,  // Cayman Islands Dollar
    KZT = 78,  // Kazakhstani Tenge
    LAK = 79,  // Lao Kip
    LBP = 80,  // Lebanese Pound
    LKR = 81,  // Sri Lankan Rupee
    LRD = 82,  // Liberian Dollar
    LSL = 83,  // Lesotho Loti
    LYD = 84,  // Libyan Dinar
    MAD = 85,  // Moroccan Dirham
    MDL = 86,  // Moldovan Leu
    MGA = 87,  // Malagasy Ariary
    MKD = 88,  // Macedonian Denar
    MMK = 89,  // Myanmar Kyat
    MNT = 90,  // Mongolian Tögrög
    MOP = 91,  // Macanese Pataca
    MRU = 92,  // Mauritanian Ouguiya
    MUR = 93,  // Mauritian Rupee
    MVR = 94,  // Maldivian Rufiyaa
    MWK = 95,  // Malawian Kwacha
    MXN = 96,  // Mexican Peso
    MYR = 97,  // Malaysian Ringgit
    MZN = 98,  // Mozambican Metical
    NAD = 99,  // Namibian Dollar
    NGN = 100, // Nigerian Naira
    NIO = 101, // Nicaraguan Córdoba
    NOK = 102, // Norwegian Krone
    NPR = 103, // Nepalese Rupee
    NZD = 104, // New Zealand Dollar
    OMR = 105, // Omani Rial
    PAB = 106, // Panamanian Balboa
    PEN = 107, // Peruvian Sol
    PGK = 108, // Papua New Guinean Kina
    PHP = 109, // Philippine Peso
    PKR = 110, // Pakistani Rupee
    PLN = 111, // Polish Złoty
    PYG = 112, // Paraguayan Guaraní
    QAR = 113, // Qatari Riyal
    RON = 114, // Romanian Leu
    RSD = 115, // Serbian Dinar
    SCR = 116, // Seychellois Rupee
    SDG = 117, // Sudanese Pound
    SEK = 118, // Swedish Krona
    SGD = 119, // Singapore Dollar
    SHP = 120, // Saint Helena Pound
    SLL = 121, // Sierra Leonean Leone
    SOS = 122, // Somali Shilling
    SRD = 123, // Surinamese Dollar
    STN = 124, // São Tomé and Príncipe Dobra
    SVC = 125, // Salvadoran Colón
    SYP = 126, // Syrian Pound
    SZL = 127, // Swazi Lilangeni
    THB = 128, // Thai Baht
    TJS = 129, // Tajikistani Somoni
    TMT = 130, // Turkmenistan Manat
    TND = 131, // Tunisian Dinar
    TOP = 132, // Tongan Paʻanga
    TRY = 133, // Turkish Lira
    TTD = 134, // Trinidad and Tobago Dollar
    TWD = 135, // New Taiwan Dollar
    TZS = 136, // Tanzanian Shilling
    UAH = 137, // Ukrainian Hryvnia
    UGX = 138, // Ugandan Shilling
    USD = 139, // United States Dollar
    UYU = 140, // Uruguayan Peso
    UZS = 141, // Uzbekistani Som
    VES = 142, // Venezuelan Bolívar
    VND = 143, // Vietnamese Đồng
    VUV = 144, // Vanuatu Vatu
    WST = 145, // Samoan Tālā
    XAF = 146, // Central African CFA Franc
    XCD = 147, // East Caribbean Dollar
    XOF = 148, // West African CFA Franc
    XPF = 149, // CFP Franc
    YER = 150, // Yemeni Rial
    ZAR = 151, // South African Rand
    ZMW = 152, // Zambian Kwacha
    ZWL = 153  // Zimbabwean Dollar
}